// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl31xCb754q8VXm4a-d8AGuHEoMUiYmFg',
    appId: '1:74333091996:web:7912029b2c89c562835559',
    messagingSenderId: '74333091996',
    projectId: 'tugas-akhir-50095',
    authDomain: 'tugas-akhir-50095.firebaseapp.com',
    databaseURL: 'https://tugas-akhir-50095-default-rtdb.firebaseio.com',
    storageBucket: 'tugas-akhir-50095.firebasestorage.app',
    measurementId: 'G-CMLSG9TBX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBThaeTc4DngK89ElCwUPNb60osz67rC1Y',
    appId: '1:74333091996:android:f332aa5a6c5c3989835559',
    messagingSenderId: '74333091996',
    projectId: 'tugas-akhir-50095',
    databaseURL: 'https://tugas-akhir-50095-default-rtdb.firebaseio.com',
    storageBucket: 'tugas-akhir-50095.firebasestorage.app',
  );
}
